language: general

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
python:
  - '3.6'

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then pyenv install -s 3.6.7 && pyenv global 3.6.7;
    fi
  - pip3 install --upgrade pip
  - pip3 install virtualenv
  - virtualenv .env -p python3
  - source .env/bin/activate
  - python --version

install:
  - pip install -r requirements.txt
  - wget https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.8.0-spark3.0-s_2.12/graphframes-0.8.0-spark3.0-s_2.12.jar

spark_envs:
  - export PYTHONPATH=:$PYTHONPATH:graphframes-0.8.0-spark3.0-s_2.12.jar
  - export PYSPARK_SUBMIT_ARGS="--packages graphframes:graphframes:0.8.0-spark3.0-s_2.12 pyspark-shell"

script:
  - pytest
