version: 2
jobs:
  build:
    docker:
      - image: elancapital/docker-java-python3
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            pytest tests_DBSCAN.py
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - store_test_results:
          path: test-results

