name: DBSCAN-PYSPARK

on:
  push: 
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    docker:
      image: elancapital/docker-java-python3
    steps:
      - uses: actions/checkout@v2
      - id: reqs
        run: pip install -r requirements.txt
      - id: tests
        run: pytest tests_DBSCAN.py
