name: DBSCAN-PYSPARK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chrsep/alpine-java-python@master
      - id: clone repo
        run: git clone https://github.com/yulevaz/DBSCAN-pyspark
      - id: reqs
        run: pip install -r ./requirements.txt
      - id: tests
        run: pytest tests_DBSCAN.py
