name: DBSCAN-PYSPARK

on:
  push: 
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: elancapital/docker-java-python3@master
      - id: reqs
        run: pip install -r requirements.txt
      - id: tests
        run: pytest tests_DBSCAN.py
