name: DBSCAN-PYSPARK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: docker
        run: docker run elancapital/docker-java-python3
      - uses: elancapital/docker-java-python3@master
      - id: reqs
        run: pip install -r requirements.txt
      - id: tests
        run: pytest tests_DBSCAN.py
